name: Test brew install
on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test brew install
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, linux-arm, macos]
        include:
        - build: linux
          os: ubuntu-22.04
        - build: linux-arm
          os: ubuntu-22.04
        - build: macos
          os: macos-12

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Install Homebrew
      run: |
        NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    - name: Install srvc
      if: matrix.build == 'linux'
      run: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew install insilica/srvc/srvc

    - name: Install srvc
      if: matrix.build == 'macos'
      run: |
        brew install insilica/srvc/srvc

    - name: Test srvc
      if: matrix.build == 'linux'
      run: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        sr help
        sr version

    - name: Test srvc
      if: matrix.build == 'macos'
      run: |
        sr help
        sr version
